[package]
name = "renderer"
version = "0.0.1"
description = "WGPU Renderer"
repository = "https://github.com/GuilhermeWerner/Renderer"
license = "MIT"
edition = "2021"
publish = false

default-run = "Renderer"

[lib]
name = "Renderer"
crate-type = ["rlib"]
path = "Source/lib.rs"

[[bin]]
name = "Renderer"
path = "Source/Main.rs"
doc = false

[[bin]]
name = "Rainbow"
path = "Source/Rainbow.rs"
doc = false

[dependencies]
anyhow = "1.0"
bytemuck = { version = "1.4", features = [ "derive" ] }
cgmath = "0.18"
env_logger = "0.9"
image = "0.23"
log = "0.4"
pollster = "0.2"
tobj = "3.0"
wgpu = "0.11"
winit = "0.25"
